[package]
name = "jellyfetch"
version = "0.0.1"
authors = ["Reese Dominguez <reesums@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]